
DELETE http://localhost:3000/produto/delete/1

###

DELETE http://localhost:3000/usuario/delete/3

###

DELETE http://localhost:3000/mesa/delete/2

###

DELETE http://localhost:3000/formapagamento/delete/5

###

DELETE http://localhost:3000/comanda/delete/11

###

DELETE http://localhost:3000/itenscomanda/delete/2

###