
DELETE http://localhost:3000/produtos/delete/111

###

DELETE http://localhost:3000/usuarios/delete/6

###

DELETE http://localhost:3000/mesa/delete/7

###

DELETE http://localhost:3000/formapagamento/delete/3

###

DELETE http://localhost:3000/pedidousuario/delete/13

###

DELETE http://localhost:3000/pedidoproduto/delete/13

###