

GET http://localhost:3000/produto

###

GET http://localhost:3000/usuario

###

GET http://localhost:3000/mesa

###


GET http://localhost:3000/formapagamento

###


GET http://localhost:3000/comanda

###


GET http://localhost:3000/itenscomanda

###
